### First stage
FROM node:16-alpine AS build

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./yarn.lock ./

RUN yarn install

COPY . .

ARG BASE_URL
ARG BLOB_KEY
ARG GEO_KEY

ENV REACT_APP_BASE_URL=${BASE_URL}
ENV REACT_APP_BLOB_STORE_SECRET_SAS_KEY=${BLOB_KEY}
ENV REACT_APP_GEOAPIFY_API_KEY=${GEO_KEY}

RUN yarn build

### Second stage
FROM nginx:stable-alpine

COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY nginx/nginx.dev.conf /etc/nginx/conf.d/default.conf

EXPOSE 81

CMD [ "nginx", "-g", "daemon off;" ]

